resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.
    [db-all:children]
    db-master
    db-slave

    [nginx]
    nginx ansible_host=${yandex_compute_instance.proxy.network_interface.0.nat_ip_address}

    [app]
    app ansible_host=${yandex_compute_instance.app.hostname}
    [app:vars]
    ansible_ssh_common_args='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${yandex_compute_instance.proxy.network_interface.0.nat_ip_address}"'
    
    [db-master]
    db-master ansible_host=${yandex_compute_instance.db01.hostname}
    [db-master:vars]
    ansible_ssh_common_args='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${yandex_compute_instance.proxy.network_interface.0.nat_ip_address}"'
    
    [db-slave]
    db-slave ansible_host=${yandex_compute_instance.db02.hostname}
    [db-slave:vars]
    ansible_ssh_common_args='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${yandex_compute_instance.proxy.network_interface.0.nat_ip_address}"'
    
    [gitlab]
    gitlab ansible_host=${yandex_compute_instance.gitlab.hostname}
    [app:vars]
    ansible_ssh_common_args='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${yandex_compute_instance.proxy.network_interface.0.nat_ip_address}"'
    
    [runner]
    runner ansible_host=${yandex_compute_instance.runner.hostname}
    [runner:vars]
    ansible_ssh_common_args='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${yandex_compute_instance.proxy.network_interface.0.nat_ip_address}"'
 
    [monitoring]
    monitoring ansible_host=${yandex_compute_instance.monitoring.hostname}
    [monitoring:vars]
    ansible_ssh_common_args='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${yandex_compute_instance.proxy.network_interface.0.nat_ip_address}"'
    
    DOC
  filename = "../ansible/inventory"

  depends_on = [
    yandex_compute_instance.app,
    yandex_compute_instance.db01,
    yandex_compute_instance.db02,
    yandex_compute_instance.proxy,
    yandex_compute_instance.gitlab,
    yandex_compute_instance.monitoring,
    yandex_compute_instance.runner
  ]
}
