---
#- name: install mysql 
 # hosts: db-all
 # become: yes
 # become_user: root
 # remote_user: ubuntu
 # roles:
 #  - {"role": db-all, "vars_file": "group_vars/all.yml"}

#- name: inastalling nginx in reverce proxy 
 # hosts: nginx
 # become: yes
 # become_user: root
 # remote_user: ubuntu
 # roles:
#   - {"role": reverse_proxy, "vars_file": "group_vars/all.yml"}

#- name: dowland and install wordpress
 # hosts: app
 # become: yes
 # become_user: root
 # remote_user: ubuntu
 # roles:
 #  - {"role": wordpress, "vars_file": "group_vars/all.yml"}


#- name: install gitlab 
 # hosts: gitlab
 # become: yes
 # become_user: root
 # remote_user: ubuntu
 # roles:
 #   - {"role": gitlab, "vars_file": "group_vars/all.yml"}

- name: install runner 
  hosts: runner
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
    - {"role": runner, "vars_file": "group_vars/all.yml"}

- name: install monitoring Prometheus Grafana
  hosts: monitoring
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
    - {"role": monitoring, "vars_file": "group_vars/all.yml"}
